version: "3.1"

services:
  php-fpm:
    build:
      context: docker/php-fpm
    container_name: example-webserver
    working_dir: /application
    volumes:
      - ./:/application
    environment:
      - WEB_DOCUMENT_ROOT=/application/www
    ports:
      - "80:80"
